// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBpYa-faY72mVHa31UZP8Tt2NhRHcqzk',
    appId: '1:886419778690:web:9a640454274322fb83989b',
    messagingSenderId: '886419778690',
    projectId: 'picture-msg',
    authDomain: 'picture-msg.firebaseapp.com',
    storageBucket: 'picture-msg.appspot.com',
    measurementId: 'G-HEN6JE3BL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRAT9kBQieJ_Non3M5xTbP9nIzX63luA',
    appId: '1:886419778690:android:624fdc9bd966f7c083989b',
    messagingSenderId: '886419778690',
    projectId: 'picture-msg',
    storageBucket: 'picture-msg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVuV6vB7oFmak_PItCOSZ0fdUGBU_IUE',
    appId: '1:886419778690:ios:f3f47bc068133a3f83989b',
    messagingSenderId: '886419778690',
    projectId: 'picture-msg',
    storageBucket: 'picture-msg.appspot.com',
    iosClientId: '886419778690-doijlfn0clvrshn2rbevev359hgcv181.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictureMsg',
  );
}
